swagger: "2.0"
info:
  description: "This API is used to get history order"
  version: "v1"
  title: "Get History Order"
paths:
  /v1/trade/order/history:
    get:
      access: "Trading Permissions"
      parameters:
        - name: "symbol"
          type: "string"
          in: query
          description: "Stock symbol, use `ticker.region` format, example: `AAPL.US`"
          required: false
        - name: "status"
          type: string[]
          in: query
          description: "[Order status](../trade-definition#orderstatus)<br/><br/>example: `status=FilledStatus&status=NewStatus`"
          required: false
        - name: side
          type: "string"
          in: query
          description: Order side<br/><br/>
            **Enum Value:**<br/>
            `Buy`<br/>
            `Sell`
          required: false
        - name: market
          type: "string"
          in: query
          description: Market<br/><br/>
            **Enum Value:**<br/>
            `US` - United States of America Market<br/>
            `HK` - Hong Kong Market
          required: false
        - name: "start_at"
          type: "string"
          required: false
          description: "Start time, formatted as a timestamp (second), example: `1650410999`"
        - name: "end_at"
          type: "string"
          required: false
          description: "End time, formatted as a timestamp (second), example: `1650410999`"
      responses:
        "200":
          description: "Get History Orders Success"
          schema:
            $ref: "#/definitions/history_orders_rsp"
        "400":
          description: "The query failed with an error in the request parameter."
      request_body:
        type: "python"
        value: |
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.longbridge.global"))

          query = {
            'symbol': '700.HK',
            'status': ['FilledStatus', 'NewStatus'],
            'side': 'Buy',
            'market': 'HK',
            'start_at': '1652111483',
            'end_at': '1652321483',
          }

          resp = http.get("/v1/trade/order/history", query)
          print(json.dumps(resp.data, indent=2))
      response_body:
        {
          "code": 0,
          "message": "success",
          "data":
            {
              "orders":
                [
                  {
                    "currency": "HKD",
                    "executed_price": "0",
                    "executed_quantity": "0",
                    "expire_date": "",
                    "last_done": "",
                    "limit_offset": "",
                    "msg": "",
                    "order_id": "701276261045858304",
                    "order_type": 1,
                    "outside_rth": 0,
                    "price": "388",
                    "quantity": "100",
                    "side": 1,
                    "status": 16,
                    "stock_name": "Tencent Holdings Ltd.",
                    "submitted_at": "1650426089",
                    "symbol": "700.HK",
                    "tag": 1,
                    "time_in_force": 0,
                    "trailing_amount": "",
                    "trailing_percent": "",
                    "trigger_at": "0",
                    "trigger_price": "",
                    "trigger_status": 0,
                    "updated_at": "1650442225",
                  },
                ],
            },
        }
definitions:
  history_orders_rsp:
    properties:
      orders:
        type: "arrary"
        description: Order Detail
        properties:
          order_id:
            type: "string"
            description: Order ID
          status:
            type: "string"
            description: "[Order Status](../trade-definition#orderstatus)"
          stock_name:
            type: "string"
            description: Stock Name
          quantity:
            type: "string"
            description: Submitted Quantity
          executed_qty:
            type: "string"
            description: Executed Quantity
          price:
            type: "string"
            description: Submitted Price
          executed_price:
            type: "string"
            description: Executed Price
          submitted_at:
            type: "string"
            description: Submitted Time
          side:
            type: "string"
            description: Order Side<br/><br/>
              **Enum Value:**<br/>
              `Buy`<br/>
              `Sell`
          symbol:
            type: "string"
            description: "Stock symbol, use `ticker.region` format, example: `AAPL.US`"
          order_type:
            type: "string"
            description: "[Order Type](../trade-definition#ordertype)"
          last_done:
            type: "string"
            description: Last done
          trigger_price:
            type: "string"
            description: "`LIT` / `MIT` Order Trigger Price"
          msg:
            type: "string"
            description: Rejected Message Or Remark
          tag:
            type: "string"
            description: Order tag<br/><br/>
              **Enum Value**<br/>
              `Normal` - Normal Order<br/>
              `GTC` - Long term Order<br/>
              `Grey` - Grey Order
          time_in_force:
            type: "string"
            description: "
              Time in force Type<br/><br/>
              **Enum Value:**<br/>
              `Day` - Day Order<br/>
              `GTC` - Good Til Canceled Order<br/>
              `GTD` - Good Til Date Order"
          expire_date:
            type: "string"
            description: "Long term order expire date, format: `YYYY-MM-DD`, example: `2022-12-05`"
          updated_at:
            type: "string"
            description: Last updated time, formatted as a timestamp (second)
          trigger_at:
            type: "string"
            description: Conditional order trigger time. formatted as a timestamp (second)
          trailing_amount:
            type: "string"
            description: "`TSMAMT` / `TSLPAMT` order trailing amount"
          trailing_percent:
            type: "string"
            description: "`TSMPCT` / `TSLPPCT` order trailing percent"
          limit_offset:
            type: "string"
            description: "`TSLPAMT` / `TSLPPCT` order limit offset amount"
          trigger_status:
            type: "string"
            description: Conditional Order Trigger Status<br/><br/>
              **Enum Value**<br/>
              `NOT_ACTIVE`<br/>
              `DEACTIVE`<br />
              `ACTIVE`<br />
              `RELEASED`
          currency:
            type: "string"
            description: Currency
          outside_rth:
            type: "string"
            description:
              Enable or disable outside regular trading hours<br/><br/>
              **Enum Value:**<br/>
              `RTH_ONLY` - Regular trading hour only<br/>
              `ANY_TIME` - Any time"
