swagger: "2.0"
info:
  description: "Submit Order for HK and US stocks, warrant and option"
  version: "v1"
  title: "Submit Order"
paths:
  /v1/trade/order:
    post:
      access: "Trading Permissions"
      parameters:
        - name: "symbol"
          type: "string"
          description: "stock symbol，use `ticker.region` format，example：`AAPL.US`"
          required: true
        - name: "order_type"
          type: "string"
          description: "[Order Type](../trade-definition#ordertype)"
          required: true
        - name: "submitted_price"
          required: false
          description: submitted price，example：`388.5`<br/><br/>
            `LO` / `ELO` / `ALO` / `ODD` / `LIT` Order Required
        - name: "submitted_quantity"
          required: true
          description: submitted quantity，example：`100`
        - name: trigger_price
          required: false
          description: trigger price，example：`388.5`<br/><br/>
            `LIT` / `MIT` Order Required
        - name: limit_offset
          required: false
          description: limit offset amount<br/><br/>
            `TSLPAMT` / `TSLPPCT` Order Required
        - name: trailing_amount
          required: false
          description: trailing amount<br/><br/>
            `TSLPAMT` / `TSMAMT` Order Required
        - name: trailing_percent
          required: false
          description: trailing percent<br/><br/>
            `TSLPPCT` / `TSMAPCT` Order Required
        - name: expire_date
          required: false
          description:
            longterm order expire date， format `YYYY-MM-DD`, example：`2022-12-05`"
            when time_in_force is `GTD` Required
        - name: side
          type: "string"
          description: Order Side<br/><br/>
            **Enum Value:**<br/>
            `Buy`<br/>
            `Sell`
          required: true
        - name: outside_rth
          required: false
          description: enabled/disable outside regular trading hours<br/><br/>
            **Enum Value:**<br/>
            `RTH_ONLY` - regular trading hour only<br/>
            `ANY_TIME` - any time"
        - name: time_in_force
          required: true
          description: "
            Time in force Type<br/><br/>
            **Enum Value:**<br/>
            `Day` - Day Order<br/>
            `GTC` - Good 'Til Canceled Order<br/>
            `GTD` - Good 'Til Date Order"
        - name: remark
          required: false
          description: "remark (Maximum 64 characters)"
      responses:
        "200":
          description: "The submission was successful and the order was commissioned."
        "400":
          description: "The submit was rejected with an incorrect request parameter."
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import Auth, Config, HttpClient
            auth = Auth("${API_KEY}", "${API_KEY_SECRET}", "${TOKEN}")
            config = Config(base_url = "https://openapi.lbkrs.com")
            client = HttpClient(auth, config)
            result = client.post("/v1/openapi/trade/order", {
              "order_type": "LO","side": "Buy","submitted_price": "388",
              "submitted_quantity": "100","symbol": "700.HK",
              "time_in_force": "Day",
            })
      response_body:
        {
          "code": 0,
          "message": "success",
          "data": { "order_id": 683615454870679552 },
        }
