swagger: "2.0"
info:
  description: "This API is used to submit order for HK and US stocks, warrant and option"
  version: "v1"
  title: "Submit Order"
paths:
  /v1/trade/order:
    post:
      access: "Trading Permissions"
      parameters:
        - name: "symbol"
          type: "string"
          description: "Stock symbol, use `ticker.region` format, example: `AAPL.US`"
          required: true
        - name: "order_type"
          type: "string"
          description: "[Order Type](../trade-definition#ordertype)"
          required: true
        - name: "submitted_price"
          required: false
          description: "Submitted price, example: `388.5`<br/><br/>
            `LO` / `ELO` / `ALO` / `ODD` / `LIT` Order Required"
        - name: "submitted_quantity"
          required: true
          description: "Submitted quantity, example: `100`"
        - name: trigger_price
          required: false
          description: "Trigger price, example: `388.5`<br/><br/>
            `LIT` / `MIT` Order Required"
        - name: limit_offset
          required: false
          description: Limit offset amount<br/><br/>
            `TSLPAMT` / `TSLPPCT` Order Required
        - name: trailing_amount
          required: false
          description: Trailing amount<br/><br/>
            `TSLPAMT` / `TSMAMT` Order Required
        - name: trailing_percent
          required: false
          description: Trailing percent<br/><br/>
            `TSLPPCT` / `TSMAPCT` Order Required
        - name: expire_date
          required: false
          description:
            "Long term order expire date, format `YYYY-MM-DD`, example: `2022-12-05`<br/><br/>
            Required when `time_in_force` is `GTD`"
        - name: side
          type: "string"
          description: Order Side<br/><br/>
            **Enum Value:**<br/>
            `Buy`<br/>
            `Sell`
          required: true
        - name: outside_rth
          required: false
          description: Enable or disable outside regular trading hours<br/><br/>
            **Enum Value:**<br/>
            `RTH_ONLY` - regular trading hour only<br/>
            `ANY_TIME` - any time"
        - name: time_in_force
          required: true
          description: "
            Time in force Type<br/><br/>
            **Enum Value:**<br/>
            `Day` - Day Order<br/>
            `GTC` - Good Til Canceled Order<br/>
            `GTD` - Good Til Date Order"
        - name: remark
          required: false
          description: "remark (Maximum 64 characters)"
      responses:
        "200":
          description: "The submission was successful and the order was commissioned."
        "400":
          description: "The submit was rejected with an incorrect request parameter."
      request_body:
        type: "python"
        value: |
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.longbridge.global"))

          payload = {
              "side": "Buy",
              "symbol": "700.HK",
              "order_type": "LO",
              "submitted_price": "50",
              "submitted_quantity": "200",
              "time_in_force": "Day",
              "remark": "Hello from Python SDK"
          }

          try:
            resp = http.post("/v1/trade/order", payload=payload)
            print(json.dumps(resp.data, indent=2))
          except Exception as e:
            print(f"Submit order error\ncode: {e.code}\nmessage: {e.message}")
      response_body:
        {
          "code": 0,
          "message": "success",
          "data": { "order_id": 683615454870679552 },
        }
