swagger: "2.0"
info:
  description: "Get Today Deals"
  version: "v1"
  title: "Get Today Deals"
paths:
  /v1/trade/order/deal/today:
    get:
      access: "Trading Permissions"
      parameters:
        - name: "symbol"
          type: "string"
          in: query
          description: "stock symbol，use `ticker.region` format，example：`AAPL.US`"
          required: false
        - name: "order_id"
          type: "string"
          required: false
          description: "Order ID，example: `701276261045858304`"
      responses:
        "200":
          description: "Get Today Deals Success"
          schema:
            $ref: "#/definitions/deals"
        "400":
          description: "The query failed with an error in the request parameter."
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import Auth, Config, HttpClient
            auth = Auth("${API_KEY}", "${API_KEY_SECRET}", "${TOKEN}")
            config = Config(base_url = "https://openapi.longbridge.global")
            client = HttpClient(auth, config)
            result = client.get("/v1/trade/order/deal/today", {"symbol": "700.HK", 
              "order_id": "693664675163312128"})
      response_body:
        {
          "code": 0,
          "message": "success",
          "data":
            {
              "trades":
                [
                  {
                    "order_id": "693664675163312128",
                    "price": "388",
                    "quantity": "100",
                    "symbol": "700.HK",
                    "trade_done_at": "1648611351",
                    "trade_id": "693664675163312128-1648611351433741210",
                  },
                ],
            },
        }
definitions:
  today_deals_rsp:
    properties:
      orders:
        type: "arrary"
        description: Deal Detail
        properties:
          order_id:
            type: "string"
            description: Order ID
          trade_id:
            type: "string"
            description: Deal ID
          symbol:
            type: "string"
            description: "stock symbol，use `ticker.region` format，example：`AAPL.US`"
          trade_done_at:
            type: "string"
            description: trade done time ，formatted as a timestamp (second)
          quantity:
            type: "string"
            description: executed quantity
          price:
            type: "string"
            description: executed price
