swagger: "2.0"
info:
  description: "Withdraw an open order"
  version: "v1"
  title: "Withdraw Order"
paths:
  /v1/trade/order:
    delete:
      access: "Trading Permissions"
      parameters:
        - name: "order_id"
          type: "string"
          description: "Order ID"
          required: true
      responses:
        "200":
          description: "The submission was successful and the order was commissioned."
        "400":
          description: "The withdrawal was rejected with an incorrect request parameter."
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import Auth, Config, HttpClient
            auth = Auth("${API_KEY}", "${API_KEY_SECRET}", "${TOKEN}")
            config = Config(base_url = "https://openapi.longbridge.global")
            client = HttpClient(auth, config)
            result = client.delete("/v1/trade/order", {"order_id": "683615454870679552"})
      response_body: { "code": 0, "message": "success" }
