swagger: "2.0"
info:
  description: "提供查询用户资金流水信息、股票、基金的持仓信息以及现金信息。"
  version: "v1"
  title: "资产相关接口"
paths:
  /v1/trade/asset/cashflow:
    get:
      summary: "查询资金流水信息"
      description: "提供资金流入/流出方向、资金类别、资金金额、发生时间、关联股票代码、资金流水说明"
      access: "接口权限"
      parameters:
        - name: "start_time"
          type: "string"
          description: "开始时间，时间戳，以 `秒` 为单位，例如：`1650037563`"
          required: false
        - name: "end_time"
          type: "string"
          description: "结束时间时间戳，以 `秒` 为单位，例如：`1650747581`"
          required: false
        - name: "business_type"
          type: "string"
          description: "资金类型 <br/><br/><b>可选值</b> <br/>`1` - 现金 <br/>`2` - 股票<br/>`3` - 基金"
          required: false
        - name: "symbol"
          type: "string"
          description: "标的代码，例如：`AAPL.US`"
          required: false
        - name: "page"
          type: "string"
          description: "起始页，默认 `1` 为单位，例如：`1`"
          required: false
        - name: "size"
          type: "string"
          description: "每页大小，默认 `50` ，例如：`50`"
          required: false

      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/cashflow_rsp"
        "202001":
          description: "内部错误"
        "202201":
          description: "获取用户信息失败，检查下账号绑定关联是否正确"
        "202202":
          description: "参数错误，检查下参数是否和要求的不一致"
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import *
            auth = Auth(APP_KEY, APP_SECRET, ACCESS_TOKEN)
            config = Config(base_url = "https://openapi.lbkrs.com")
            client = Client(auth, config)
            result = client.get("/v1/openapi/asset/cashflow")
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "transaction_flow_name": "股票买入成交",
                    "direction": 1,
                    "balance": "-248.60",
                    "currency": "USD",
                    "business_time": 1621507957,
                    "symbol": "AAPL.US",
                    "description": "AAPL",
                  },
                  {
                    "transaction_flow_name": "股票买入成交",
                    "direction": 1,
                    "balance": "-125.16",
                    "currency": "USD",
                    "business_time": 1621504824,
                    "symbol": "AAPL.US",
                    "description": "AAPL",
                  },
                ],
            },
        }
  /v1/trade/asset/stock:
    get:
      summary: "股票持仓"
      description: "提供包括账户、股票代码、持仓股数、可用股数、持仓均价（按账户设置计算均价方式）、币种在内的持仓信"
      access: "接口权限"
      parameters:
        - name: "symbol"
          type: "string[]"
          description: "基金代码，使用 `ticker.region` 格式，例如：`AAPL.US`"
          required: false
      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/stock_rsp"
        "202001":
          description: "内部错误"
        "202201":
          description: "获取用户信息失败，检查下账号绑定关联是否正确"
        "202202":
          description: "参数错误，检查下参数是否和要求的不一致"
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import *
            auth = Auth(APP_KEY, APP_SECRET, ACCESS_TOKEN)
            config = Config(base_url = "https://openapi.lbkrs.com")
            client = Client(auth, config)
            result = client.get("/v1/openapi/asset/stock")
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "account_channel": "lb",
                    "stock_info":
                      [
                        {
                          "symbol": "700.HK",
                          "symbol_name": "腾讯控股",
                          "currency": "HK",
                          "quality": "650",
                          "available_quality": "-450",
                          "cost_price": "457.53",
                        },
                        {
                          "symbol": "9991.HK",
                          "symbol_name": "宝尊电商-SW",
                          "currency": "HK",
                          "quality": "200",
                          "available_quality": "0",
                          "cost_price": "32.25",
                        },
                        {
                          "symbol": "TCEHY.US",
                          "symbol_name": "腾讯控股 (ADR)",
                          "currency": "US",
                          "quality": "10",
                          "available_quality": "10",
                        },
                        {
                          "symbol": "2628.HK",
                          "symbol_name": "中国人寿",
                          "currency": "HK",
                          "quality": "9000",
                          "available_quality": "0",
                        },
                        {
                          "symbol": "5.HK",
                          "symbol_name": "汇丰控股",
                          "currency": "HK",
                          "quality": "2400",
                          "available_quality": "2000",
                        },
                        {
                          "symbol": "BABA.US",
                          "symbol_name": "阿里巴巴",
                          "currency": "US",
                          "quality": "2000209",
                          "available_quality": "2000209",
                        },
                        {
                          "symbol": "2.HK",
                          "symbol_name": "中电控股",
                          "currency": "HK",
                          "quality": "2000",
                          "available_quality": "2000",
                        },
                        {
                          "symbol": "NOK.US",
                          "symbol_name": "诺基亚",
                          "currency": "US",
                          "quality": "1",
                          "available_quality": "0",
                        },
                      ],
                  },
                ],
            },
        }
  /v1/trade/asset/fund:
    get:
      summary: "基金持仓"
      description: "用户基金持仓信息"
      access: "接口权限"
      parameters:
        - name: "symbol"
          type: "string[]"
          description: "基金代码，使用 `isin` 格式，例如：`HK0000676327`"
          required: false
      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/fund_rsp"
        "202001":
          description: "内部错误"
        "202201":
          description: "获取用户信息失败，检查下账号绑定关联是否正确"
        "202202":
          description: "参数错误，检查下参数是否和要求的不一致"
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import *
            auth = Auth(APP_KEY, APP_SECRET, ACCESS_TOKEN)
            config = Config(base_url = "https://openapi.lbkrs.com")
            client = Client(auth, config)
            result = client.get("/v1/openapi/asset/fund")
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "account_channel": "lb",
                    "fund_info":
                      [
                        {
                          "symbol": "HK0000447943",
                          "symbol_name": "GAOTENG EMERGING MARKETS PLUS  LONG/SHORT FIXED INCOME ALPHA FUND",
                          "currency": "USD",
                          "holding_units": "5.000",
                          "current_net_asset_value": "0",
                          "cost_net_asset_value": "0.00",
                          "net_asset_value_day": 1649865600,
                        },
                      ],
                  },
                ],
            },
        }
  /v1/trade/asset/accountcashinfo:
    get:
      summary: "查询账户资金信息"
      description: "返回每个币种可用、可取、冻结、待结算金额、在途资金（基金申购赎回)"
      access: "接口权限"
      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/accountcash_rsp"
        "202001":
          description: "内部错误"
        "202201":
          description: "获取用户信息失败，检查下账号绑定关联是否正确"
        "202202":
          description: "参数错误，检查下参数是否和要求的不一致"
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import *
            auth = Auth(APP_KEY, APP_SECRET, ACCESS_TOKEN)
            config = Config(base_url = "https://openapi.lbkrs.com")
            client = Client(auth, config)
            result = client.get("/v1/openapi/asset/accountcashinfo")
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "total_cash": "1759070010.72",
                    "max_finance_amount": "977582000",
                    "remaining_finance_amount": "0",
                    "risk_level": "1",
                    "margin_call": "2598051051.50",
                    "currency": "HKD",
                    "cashInfos":
                      [
                        {
                          "withdraw_cash": "97592.30",
                          "available_cash": "195902464.37",
                          "frozen_cash": "11579339.13",
                          "settling_cash": "207288537.81",
                          "currency": "HKD",
                        },
                        {
                          "withdraw_cash": "199893416.74",
                          "available_cash": "199893416.74",
                          "frozen_cash": "28723.76",
                          "settling_cash": "-276806.51",
                          "currency": "USD",
                        },
                      ],
                  },
                ],
            },
        }

definitions:
  cashflow_rsp:
    properties:
      list:
        type: "arrary"
        description: 流水信息
        properties:
          transaction_flow_name:
            type: string
            description: 流水名称
          direction:
            type: "string"
            description: 流出方向 <br/><br/><b>可选值:</b> <br/>`1` - 流出 <br/>  `2` - 流入
          business_type:
            type: "string"
            description: 资金类别 <br/><br/><b>可选值:</b> <br/>`1` - 现金 <br/> `2` - 股票 <br/> `3` - 基金
          balance:
            type: "string"
            description: 资金金额
          currency:
            type: "string"
            description: 资金币种
          business_time:
            type: "string"
            description: 业务时间
          symbol:
            type: "string"
            description: 关联股票代码信息
            required: true
          description:
            type: "string"
            description: 资金流水说明
  stock_rsp:
    properties:
      list:
        type: "arrary"
        description: "股票持仓信息"
        properties:
          account_channel:
            type: string
            description: 账户类型
          stock_info:
            type: "arrary"
            description: 股票列表
            properties:
              symbol:
                type: "string"
                description: 股票代码
              symbol_name:
                type: "string"
                description: 股票名称
              quality:
                type: "string"
                description: 持仓股数
              available_quality:
                type: "string"
                description: 可用股数
              currency:
                type: "string"
                description: 币种
              cost_price:
                type: "string"
                description: 成本价格 (具体根据客户端选择平均买入还是摊薄成本)
  fund_rsp:
    properties:
      list:
        type: "arrary"
        description: "股票持仓信息"
        properties:
          account_channel:
            type: string
            description: 账户类型
          fund_info:
            type: "arrary"
            description: 基金详情
            properties:
              symbol:
                type: "string"
                description: 基金 isin 代码
              current_net_asset_value:
                type: "string"
                description: 当前净值
              net_asset_value_day:
                type: "string"
                description: 当前净值时间
              symbol_name:
                type: "string"
                description: 基金名称
              currency:
                type: "string"
                description: 币种
              cost_net_asset_value:
                type: "string"
                description: 成本净值

  accountcash_rsp:
    properties:
      list:
        type: "arrary"
        description: 账户资金信息
        properties:
          total_cash:
            type: "string"
            description: 现金总额
          max_finance_amount:
            type: "string"
            description: 最大融资金额
          remaining_finance_amount:
            type: "string"
            description: 剩余融资金额
          risk_level:
            type: "string"
            description: 风控等级 <br/> <br/> <b>可选值:</b><br/> `1` - 低风险 <br/> `2` - 中低风险<br/> `3` - 中风险<br/> `4` - 中高风险 <br/> `5` - 高风险
          margin_call:
            type: "string"
            description: 追缴保证金
          currency:
            type: "string"
            description: 币种
          cashInfos:
            type: "object"
            description: 现金详情
            properties:
              withdraw_cash:
                type: "string"
                description: 可提现金
              available_cash:
                type: "string"
                description: 可用现金
              frozen_cash:
                type: "string"
                description: 冻结现金
              settling_cash:
                type: "string"
                description: 待结算现金
              currency:
                type: "string"
                description: 币种
                required: true
