swagger: "2.0"
info:
  description: "提供资金流入/流出方向、资金类别、资金金额、发生时间、关联股票代码、资金流水说明"
  version: "v1"
  title: "获取资金流水信息"
paths:
  /v1/openapi/asset/cashflow:
    get:
      access:
      parameters:
        - name: "start_time"
          type: "string"
          description: "开始时间，时间戳，以 `秒` 为单位，例如：`1650037563`"
          required: false
        - name: "end_time"
          type: "string"
          description: "结束时间时间戳，以 `秒` 为单位，例如：`1650747581`"
          required: false
        - name: "business_type"
          type: "string"
          description: "资金类型 <br/><br/> <b>可选值:</b> <br/>`1` - 现金 <br/>`2` - 股票<br/> `3` - 基金"
          required: falsegit pull
        - name: "symbol"
          type: "string"
          description: "标的代码，例如：`AAPL.US`"
          required: false
        - name: "page"
          type: "string"
          description: "起始页，默认 `1` 为单位，例如：`1`"
          required: false
        - name: "size"
          type: "string"
          description: "每页大小，默认 `50` ，例如：`50`"
          required: false

      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/cashflow_rsp"
        "202001":
          description: "内部错误"
        "202201":
          description: "获取用户信息失败，检查下账号绑定关联是否正确"
        "202202":
          description: "参数错误，检查下参数是否和要求的不一致"
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import *
            auth = Auth(APP_KEY, APP_SECRET, ACCESS_TOKEN)
            config = Config(base_url = "https://openapi.lbkrs.com")
            client = Client(auth, config)
            result = client.get("/v1/openapi/asset/cashflow")
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "transaction_flow_name": "股票买入成交",
                    "direction": 1,
                    "balance": "-248.60",
                    "currency": "USD",
                    "business_time": 1621507957,
                    "symbol": "AAPL.US",
                    "description": "AAPL",
                  },
                  {
                    "transaction_flow_name": "股票买入成交",
                    "direction": 1,
                    "balance": "-125.16",
                    "currency": "USD",
                    "business_time": 1621504824,
                    "symbol": "AAPL.US",
                    "description": "AAPL",
                  },
                ],
            },
        }

definitions:
  cashflow_rsp:
    properties:
      list:
        type: "arrary"
        description: 流水信息
        properties:
          transaction_flow_name:
            type: string
            description: 流水名称
          direction:
            type: "string"
            description: 流出方向 <br/><br/><b>可选值:</b> <br/>`1` - 流出 <br/>  `2` - 流入
          business_type:
            type: "string"
            description: 资金类别 <br/><br/><b>可选值:</b> <br/>`1` - 现金 <br/> `2` - 股票 <br/> `3` - 基金
          balance:
            type: "string"
            description: 资金金额
          currency:
            type: "string"
            description: 资金币种
          business_time:
            type: "string"
            description: 业务时间
          symbol:
            type: "string"
            description: 关联股票代码信息
            required: true
          description:
            type: "string"
            description: 资金流水说明
