swagger: "2.0"
info:
  description: "The API is used to obtain the available, desirable, frozen, to-be-settled, and in-transit funds (fund purchase and redemption) information for each currency of the user"
  version: "v1"
  title: "Get Account Balance"
paths:
  /v1/asset/account:
    get:
      access:
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/accountcash_rsp"
        "202001":
          description: "Internal Error"
        "202201":
          description: "Failed to obtain user information, check whether the account binding association is correct"
        "202202":
          description: "Parameter error, check whether the parameters are inconsistent with the requirements"
      request_body:
        type: "python"
        value: |
          from longbridge.http import Auth, Config, HttpClient

          URL = "https://openapi.lbkrs.com"

          def example():
              """
              下单接口
                  前置条件：账号需要有充足金额
              """
              auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
              config = Config(base_url=URL)
              client = HttpClient(auth, config)
              result = client.get("/v1/asset/account")
              print(result.data)

          if __name__ == "__main__":
              example()
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "total_cash": "1759070010.72",
                    "max_finance_amount": "977582000",
                    "remaining_finance_amount": "0",
                    "risk_level": "1",
                    "margin_call": "2598051051.50",
                    "currency": "HKD",
                    "cashInfos":
                      [
                        {
                          "withdraw_cash": "97592.30",
                          "available_cash": "195902464.37",
                          "frozen_cash": "11579339.13",
                          "settling_cash": "207288537.81",
                          "currency": "HKD",
                        },
                        {
                          "withdraw_cash": "199893416.74",
                          "available_cash": "199893416.74",
                          "frozen_cash": "28723.76",
                          "settling_cash": "-276806.51",
                          "currency": "USD",
                        },
                      ],
                  },
                ],
            },
        }

definitions:
  accountcash_rsp:
    properties:
      list:
        type: "arrary"
        description: Account Balance
        properties:
          total_cash:
            type: "string"
            description: Total Cash
          max_finance_amount:
            type: "string"
            description: Maximum Financing Amount
          remaining_finance_amount:
            type: "string"
            description: Remaining Financing Amount
          risk_level:
            type: "string"
            description: Risk control level  <br/> <br/> <b>Option:</b><br/> `1` - low risk <br/> `2` - low to medium risk<br/> `3` - medium risk<br/> `4` - medium to high risk  <br/> `5` - high risk
          margin_call:
            type: "string"
            description: Margin Call
          currency:
            type: "string"
            description: Currency
          cashInfos:
            type: "object"
            description: Cash Details
            properties:
              withdraw_cash:
                type: "string"
                description: Withdraw Cash
              available_cash:
                type: "string"
                description: Available Cash
              frozen_cash:
                type: "string"
                description: Frozen Cash
              settling_cash:
                type: "string"
                description: Cash to be Settled
              currency:
                type: "string"
                description: Currency
                required: true
