swagger: "2.0"
info:
  description: "The API is used to obtain capital inflow/outflow direction, capital type, capital amount, occurrence time, associated stock code and capital flow description information"
  version: "v1"
  title: "Get Cash Flow"
paths:
  /v1/asset/cashflow:
    get:
      access:
      parameters:
        - name: "start_time"
          type: "string"
          description: "start time timestamp，in `seconds`，E.g：`1650037563`"
          required: true
        - name: "end_time"
          type: "string"
          description: "end time timestamp，in `seconds`，E.g：`1650747581`"
          required: true
        - name: "business_type"
          type: "string"
          description: "Balance type<br/><br/> <b>Option:</b> <br/>`1` - cash <br/>`2` - stock<br/> `3` - fund"
          required: false
        - name: "symbol"
          type: "string"
          description: "Target code，E.g：`AAPL.US`"
          required: false
        - name: "page"
          type: "string"
          description: "start page <br/><br/><b>Default value:</b> `1`  <br/><b>Data validation rules:</b><br/> <b>Ranges:</b> `>=1`"
          required: false
        - name: "size"
          type: "string"
          description: "page size <br/><br/><b>Default value:</b> `50` <br/><b>Data validation rules:</b> `1~10000`"
          required: false

      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/cashflow_rsp"
        "400":
          description: "Internal Error"
      request_body:
        type: "python"
        value: |
          # Get Cash Flow
          # https://open.longbridgeapp.com/docs/trade/asset/cashflow
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.lbkrs.com"))

          resp = http.get("/v1/asset/cashflow",{"start_time":"1623881671","end_time":"1626881673"})
          print(json.dumps(resp.data, indent=2))
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "transaction_flow_name": "BuyContract-Stocks",
                    "direction": 1,
                    "balance": "-248.60",
                    "currency": "USD",
                    "business_time": 1621507957,
                    "symbol": "AAPL.US",
                    "description": "AAPL",
                  },
                  {
                    "transaction_flow_name": "BuyContract-Stocks",
                    "direction": 1,
                    "balance": "-125.16",
                    "currency": "USD",
                    "business_time": 1621504824,
                    "symbol": "AAPL.US",
                    "description": "AAPL",
                  },
                ],
            },
        }

definitions:
  cashflow_rsp:
    properties:
      list:
        type: "arrary"
        description: Cash flow info
        properties:
          transaction_flow_name:
            type: string
            description: Cash flow name
          direction:
            type: "string"
            description: outflow direction <br/><br/><b>Option:</b> <br/>`1` - outflow <br/>  `2` - inflow
          business_type:
            type: "string"
            description: Funding Category <br/><br/><b>Option:</b> <br/>`1` - cash <br/> `2` - stock <br/> `3` - fund
          balance:
            type: "string"
            description: Cash amount
          currency:
            type: "string"
            description: Cash Currency
          business_time:
            type: "string"
            description: business time
          symbol:
            type: "string"
            description: associated Stock code information
            required: true
          description:
            type: "string"
            description: Cash flow description
