swagger: "2.0"
info:
  description: "This interface is used to obtain fund position information including account, fund code, holding share, cost net worth, current net worth, and currency."
  version: "v1"
  title: "Get fund positions"
paths:
  /v1/asset/fund:
    get:
      access:
      parameters:
        - name: "symbol"
          type: "string[]"
          description: fund code, in `ISIN` format，E.g：`HK0000676327` <a href="https://en.wikipedia.org/wiki/International_Securities_Identification_Number">ISIN explain</a>
          required: false
      responses:
        "200":
          description: "success"
          schema:
            $ref: "#/definitions/fund_rsp"
        "202001":
          description: "internal error"
        "202201":
          description: "Failed to obtain user information, check whether the account binding association is correct"
        "202202":
          description: "Parameter error, check whether the parameters are inconsistent with the requirements"
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import Auth, Config, HttpClient
            auth = Auth("${APP_KEY}", "${APP_SECRET}", "${ACCESS_TOKEN}")
            config = Config(base_url = "https://openapi.lbkrs.com")
            client = HttpClient(auth, config)
            result = client.get("/v1/asset/fund")
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "account_channel": "lb",
                    "fund_info":
                      [
                        {
                          "symbol": "HK0000447943",
                          "symbol_name": "GAOTENG EMERGING MARKETS PLUS  LONG/SHORT FIXED INCOME ALPHA FUND",
                          "currency": "USD",
                          "holding_units": "5.000",
                          "current_net_asset_value": "0",
                          "cost_net_asset_value": "0.00",
                          "net_asset_value_day": 1649865600,
                        },
                      ],
                  },
                ],
            },
        }

definitions:
  fund_rsp:
    properties:
      list:
        type: "arrary"
        description: "stock holding information"
        properties:
          account_channel:
            type: string
            description: account type
          fund_info:
            type: "arrary"
            description: fund Details
            properties:
              symbol:
                type: "string"
                description: fund isin code
              current_net_asset_value:
                type: "string"
                description: current equity
              net_asset_value_day:
                type: "string"
                description: current equity time
              symbol_name:
                type: "string"
                description: fund name
              currency:
                type: "string"
                description: currency
              cost_net_asset_value:
                type: "string"
                description: net cost
