swagger: "2.0"
info:
  description: "該接口用於修改訂單的價格，數量"
  version: "v1"
  title: "修改訂單"
paths:
  /v1/trade/order/replace:
    post:
      access: "交易權限"
      parameters:
        - name: "order_id"
          type: "string"
          description: "訂單 ID"
          required: true
        - name: "quantity"
          type: "string"
          description: "改單數量，例如: `200`"
          required: true
        - name: "price"
          required: false
          description: 改單價格，例如：`388.5`<br/><br/>
            `LO` / `ELO` / `ALO` / `ODD` / `LIT` 訂單必填
        - name: trigger_price
          required: false
          description: 觸發價格，例如：`388.5`<br/><br/>
            `LIT` / `MIT` 訂單必填
        - name: limit_offset
          required: false
          description: 指定價差<br/><br/>
            `TSLPAMT` / `TSLPPCT` 訂單必填
        - name: trailing_amount
          required: false
          description: 跟蹤金額<br/><br/>
            `TSLPAMT` / `TSMAMT` 訂單必填
        - name: trailing_percent
          required: false
          description: 跟蹤漲跌幅<br/><br/>
            `TSLPPCT` / `TSMAPCT` 訂單必填
        - name: remark
          required: false
          description: "備註 (最大 64 字符)"
      responses:
        "200":
          description: "提交成功，訂單已委托。"
        "400":
          description: "下單被拒絕，請求參數錯誤。"
      request_body:
        type: "python"
        value: |
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.lbkrs.com"))

          payload = {
              "side": "Buy",
          }

          try:
            resp = http.post("/v1/trade/order/replace", payload=payload)
            print(json.dumps(resp.data, indent=2))
          except Exception as e:
            print(f"Submit order error\ncode: {e.code}\nmessage: {e.message}")
      response_body: { "code": 0, "message": "success", "data": {} }
