swagger: "2.0"
info:
  description: "該接口用於獲取用戶每個幣種可用、可取、凍結、待結算金額、在途資金 (基金申購贖回) 信息"
  version: "v1"
  title: "獲取賬戶資金"
paths:
  /v1/asset/account:
    get:
      access:
      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/accountcash_rsp"
        "400":
          description: "內部錯誤"
      request_body:
        type: "python"
        value: |
          # 獲取賬戶資金
          # https://open.longbridgeapp.com/docs/trade/asset/account
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.lbkrs.com"))

          resp = http.get("/v1/asset/account")
          print(json.dumps(resp.data, indent=2))
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "total_cash": "1759070010.72",
                    "max_finance_amount": "977582000",
                    "remaining_finance_amount": "0",
                    "risk_level": "1",
                    "margin_call": "2598051051.50",
                    "currency": "HKD",
                    "cash_infos":
                      [
                        {
                          "withdraw_cash": "97592.30",
                          "available_cash": "195902464.37",
                          "frozen_cash": "11579339.13",
                          "settling_cash": "207288537.81",
                          "currency": "HKD",
                        },
                        {
                          "withdraw_cash": "199893416.74",
                          "available_cash": "199893416.74",
                          "frozen_cash": "28723.76",
                          "settling_cash": "-276806.51",
                          "currency": "USD",
                        },
                      ],
                  },
                ],
            },
        }

definitions:
  accountcash_rsp:
    properties:
      list:
        type: "arrary"
        description: 賬戶資金信息
        properties:
          total_cash:
            type: "string"
            description: 現金總額
          max_finance_amount:
            type: "string"
            description: 最大融資金額
          remaining_finance_amount:
            type: "string"
            description: 剩餘融資金額
          risk_level:
            type: "string"
            description: 風控等級  <br/> <br/> <b>可選值:</b><br/> `1` - 低風險  <br/> `2` - 中低風險<br/> `3` - 中風險<br/> `4` - 中高風險 <br/> `5` - 高風險
          margin_call:
            type: "string"
            description: 追繳保證金
          currency:
            type: "string"
            description: 幣種
          cash_infos:
            type: "object"
            description: 現金詳情
            properties:
              withdraw_cash:
                type: "string"
                description: 可提現金
              available_cash:
                type: "string"
                description: 可用現金
              frozen_cash:
                type: "string"
                description: 凍結現金
              settling_cash:
                type: "string"
                description: 待結算現金
              currency:
                type: "string"
                description: 幣種
                required: true
