swagger: "2.0"
info:
  description: "該接口用於獲取資金流入/流出方向、資金類別、資金金額、發生時間、關聯股票代碼和資金流水說明信息"
  version: "v1"
  title: "獲取資金流水"
paths:
  /v1/asset/cashflow:
    get:
      access:
      parameters:
        - name: "start_time"
          type: "string"
          description: "开始时间，时间戳，以 `秒` 为单位，例如：`1650037563`"
          required: true
        - name: "end_time"
          type: "string"
          description: "结束时间时间戳，以 `秒` 为单位，例如：`1650747581`"
          required: true
        - name: "business_type"
          type: "string"
          description: "资金类型 <br/><br/> <b>可选值:</b> <br/>`1` - 现金 <br/>`2` - 股票<br/> `3` - 基金"
          required: false
        - name: "symbol"
          type: "string"
          description: "标的代码，例如：`AAPL.US`"
          required: false
        - name: "page"
          type: "string"
          description: "起始页 <br/><br/><b>默认值:</b> `1`  <br/><b>数据校验规则:</b><br/> <b>取值范围:</b> `>=1`"
          required: false
        - name: "size"
          type: "string"
          description: "每页大小 <br/><br/><b>默认值:</b> `50` <br/><b>数据校验规则:</b> `1~10000`"
          required: false

      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/cashflow_rsp"
        "202001":
          description: "內部錯誤"
        "202201":
          description: "獲取用戶信息失敗，檢查下賬號綁定關聯是否正確"
        "202202":
          description: "參數錯誤，檢查下參數是否和要求的不一致"
      request_body:
        type: "python"
        value: |
          from longbridge.http import Auth, Config, HttpClient

                    URL = "https://openapi.lbkrs.com"

                    def example():
                        """
                        下单接口
                            前置条件：账号需要有充足金额
                        """
                        auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
                        config = Config(base_url=URL)
                        client = HttpClient(auth, config)
                        result = client.get("/v1/asset/cashflow",{"start_time":"1623881671","end_time":"1626881673"})
                        print(result.data)

                    if __name__ == "__main__":
                        example()
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "transaction_flow_name": "股票買入成交",
                    "direction": 1,
                    "balance": "-248.60",
                    "currency": "USD",
                    "business_time": 1621507957,
                    "symbol": "AAPL.US",
                    "description": "AAPL",
                  },
                  {
                    "transaction_flow_name": "股票買入成交",
                    "direction": 1,
                    "balance": "-125.16",
                    "currency": "USD",
                    "business_time": 1621504824,
                    "symbol": "AAPL.US",
                    "description": "AAPL",
                  },
                ],
            },
        }

definitions:
  cashflow_rsp:
    properties:
      list:
        type: "arrary"
        description: 流水信息
        properties:
          transaction_flow_name:
            type: string
            description: 流水名稱
          direction:
            type: "string"
            description: 流出方向 <br/><br/><b>可選值:</b> <br/>`1` - 流出 <br/>  `2` - 流入
          business_type:
            type: "string"
            description: 资金类别 <br/><br/><b>可選值:</b> <br/>`1` - 現金 <br/> `2` - 股票 <br/> `3` - 基金
          balance:
            type: "string"
            description: 資金金額
          currency:
            type: "string"
            description: 資金幣種
          business_time:
            type: "string"
            description: 業務時間
          symbol:
            type: "string"
            description: 關聯股票代碼信息
            required: true
          description:
            type: "string"
            description: 資金流水說明
