swagger: "2.0"
info:
  description: "該接口用於獲取包括賬戶、基金代碼、持有份額、成本淨值、當前淨值、幣種在內的基金持倉信息"
  version: "v1"
  title: "獲取基金持倉"
paths:
  /v1/asset/fund:
    get:
      access:
      parameters:
        - name: "symbol"
          type: "string[]"
          description: 基金代碼，使用 `ISIN` 格式，例如：`HK0000676327` <a href="https://en.wikipedia.org/wiki/International_Securities_Identification_Number">ISIN 解釋</a>
          required: false
      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/fund_rsp"
        "202001":
          description: "內部錯誤"
        "202201":
          description: "獲取用戶信息失敗，檢查下賬號綁定關聯是否正確"
        "202202":
          description: "參數錯誤，檢查下參數是否和要求的不一致"
      request_body:
        type: "python"
        value: |
          from longbridge.http import Auth, Config, HttpClient

                    URL = "https://openapi.lbkrs.com"

                    def example():
                        """
                        下单接口
                            前置条件：账号需要有充足金额
                        """
                        auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
                        config = Config(base_url=URL)
                        client = HttpClient(auth, config)
                        result = client.get("/v1/asset/fund")
                        print(result.data)

                    if __name__ == "__main__":
                        example()
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "account_channel": "lb",
                    "fund_info":
                      [
                        {
                          "symbol": "HK0000447943",
                          "symbol_name": "高騰亞洲收益基金",
                          "currency": "USD",
                          "holding_units": "5.000",
                          "current_net_asset_value": "0",
                          "cost_net_asset_value": "0.00",
                          "net_asset_value_day": 1649865600,
                        },
                      ],
                  },
                ],
            },
        }

definitions:
  fund_rsp:
    properties:
      list:
        type: "arrary"
        description: "股票持倉信息"
        properties:
          account_channel:
            type: string
            description: 賬戶類型
          fund_info:
            type: "arrary"
            description: 基金詳情
            properties:
              symbol:
                type: "string"
                description: 基金 ISIN 代碼
              current_net_asset_value:
                type: "string"
                description: 當前淨值
              net_asset_value_day:
                type: "string"
                description: 當前淨值時間
              symbol_name:
                type: "string"
                description: 基金名稱
              currency:
                type: "string"
                description: 幣種
              cost_net_asset_value:
                type: "string"
                description: 成本淨值
