swagger: "2.0"
info:
  description: "該接口用於獲取包括賬戶、股票代碼、持倉股數、可用股數、持倉均價（按賬戶設置計算均價方式）、幣種在內的股票持倉信息"
  version: "v1"
  title: "獲取股票持倉"
paths:
  /v1/asset/stock:
    get:
      access:
      parameters:
        - name: "symbol"
          type: "string[]"
          description: "股票代碼，使用 `ticker.region` 格式，例如：`AAPL.US`"
          required: false
      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/stock_rsp"
        "400":
          description: "內部錯誤"
      request_body:
        type: "python"
        value: |
          # 獲取股票持倉
          # https://open.longbridgeapp.com/docs/trade/asset/stock
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.lbkrs.com"))

          resp = http.get("/v1/asset/stock?symbol=700.HK&symbol=BABA.US")
          print(json.dumps(resp.data, indent=2))
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "account_channel": "lb",
                    "stock_info":
                      [
                        {
                          "symbol": "700.HK",
                          "symbol_name": "騰訊控股",
                          "currency": "HK",
                          "quality": "650",
                          "available_quality": "-450",
                          "cost_price": "457.53",
                        },
                        {
                          "symbol": "9991.HK",
                          "symbol_name": "寶尊電商-SW",
                          "currency": "HK",
                          "quality": "200",
                          "available_quality": "0",
                          "cost_price": "32.25",
                        },
                        {
                          "symbol": "TCEHY.US",
                          "symbol_name": "騰訊控股 (ADR)",
                          "currency": "US",
                          "quality": "10",
                          "available_quality": "10",
                        },
                        {
                          "symbol": "2628.HK",
                          "symbol_name": "中國人壽",
                          "currency": "HK",
                          "quality": "9000",
                          "available_quality": "0",
                        },
                        {
                          "symbol": "5.HK",
                          "symbol_name": "匯豐控股",
                          "currency": "HK",
                          "quality": "2400",
                          "available_quality": "2000",
                        },
                        {
                          "symbol": "BABA.US",
                          "symbol_name": "阿里巴巴",
                          "currency": "US",
                          "quality": "2000209",
                          "available_quality": "2000209",
                        },
                        {
                          "symbol": "2.HK",
                          "symbol_name": "中電控股",
                          "currency": "HK",
                          "quality": "2000",
                          "available_quality": "2000",
                        },
                        {
                          "symbol": "NOK.US",
                          "symbol_name": "諾基亞",
                          "currency": "US",
                          "quality": "1",
                          "available_quality": "0",
                        },
                      ],
                  },
                ],
            },
        }

definitions:
  stock_rsp:
    properties:
      list:
        type: "arrary"
        description: "股票持倉信息"
        properties:
          account_channel:
            type: string
            description: 賬戶類型
          stock_info:
            type: "arrary"
            description: 股票列表
            properties:
              symbol:
                type: "string"
                description: 股票代碼
              symbol_name:
                type: "string"
                description: 股票名稱
              quality:
                type: "string"
                description: 持倉股數
              available_quality:
                type: "string"
                description: 可用股數
              currency:
                type: "string"
                description: 幣種
              cost_price:
                type: "string"
                description: 成本價格 (具體根據客戶端選擇平均買入還是攤薄成本)
