swagger: "2.0"
info:
  description: "该接口用于订单撤销"
  version: "v1"
  title: "撤销订单"
paths:
  /v1/trade/order:
    delete:
      access: "交易权限"
      parameters:
        - name: "order_id"
          type: "string"
          description: "订单 ID"
          required: true
      responses:
        "200":
          description: "提交成功，订单已委托。"
        "400":
          description: "撤单被拒绝，请求参数错误。"
      request_body:
        type: "python"
        value: |
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.longbridge.global"))

          payload = {
              "order_id": "709043056541253632",
          }

          try:
            resp = http.delete("/v1/trade/order", payload=payload)
            print(json.dumps(resp.data, indent=2))
          except Exception as e:
            print(f"Submit order error\ncode: {e.code}\nmessage: {e.message}")
      response_body: { "code": 0, "message": "success", "data": {} }
