swagger: "2.0"
info:
  description: "历史订单查询"
  version: "v1"
  title: "历史订单查询"
paths:
  /v1/trade/order/history:
    get:
      access: "交易权限"
      parameters:
        - name: "symbol"
          type: "string"
          in: query
          description: "股票代码，使用 `ticker.region` 格式，例如：`AAPL.US`"
          required: false
        - name: "status"
          type: string[]
          in: query
          description: "
            订单状态<br/><br/>
            **可选项:**<br/>
            * `NotReported` -	待提交<br/>
            * `ReplacedNotReported` -	待提交 (改单成功)<br/>
            * `ProtectedNotReported` -	待提交 (保价订单)<br/>
            * `VarietiesNotReported` -	待提交 (条件单)<br/>
            * `FilledStatus` -	已成交<br/>
            * `WaitToNew` -	已提待报<br/>
            * `NewStatus` -	已委托<br/>
            * `WaitToReplace` -	修改待报<br/>
            * `PendingReplaceStatus` -	待修改<br/>
            * `ReplacedStatus` -	已修改<br/>
            * `PartialFilledStatus` -	部分成交<br/>
            * `WaitToCancel` -	撤销待报<br/>
            * `PendingCancelStatus` -	待撤回<br/>
            * `RejectedStatus` -	已拒绝<br/>
            * `CanceledStatus` -	已撤单<br/>
            * `ExpiredStatus` -	已过期<br/>
            `PartialWithdrawal` -	部分撤单<br/>"
          required: false
        - name: side
          type: "string"
          in: query
          description: "
            买卖方向<br/><br/>
            **可选项:**<br/>
            * `Buy` - 买入<br/>
            * `Sell` - 卖出"
          required: false
        - name: market
          type: "string"
          in: query
          description: "
            市场<br/><br/>
            **可选项:**<br/>
            * `US` - 美股<br/>
            * `HK` - 港股"
          required: false
        - name: "start_at"
          type: "string"
          required: false
          description: "开始时间，格式为时间戳 (秒)，例如: `1650410999`"
        - name: "end_at"
          type: "string"
          required: false
          description: "结束时间，格式为时间戳 (秒)，例如: `1650410999`"
      responses:
        "200":
          description: "提交成功，订单已委托."
          schema:
            $ref: "#/definitions/orders"
        "400":
          description: "下单被拒绝，请求参数错误."
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import *
            auth = Auth("${API_KEY}", "${API_KEY_SECRET}", "${TOKEN}")
            config = Config(base_url = "https://open.longbridgeapp.com/")
            client = Client(auth, config)
            result = client.get("/v1/trade/order/history")
      response_body:
        {
          "code": 0,
          "data":
            {
              "orders":
                [
                  {
                    "currency": "HKD",
                    "executed_price": "0",
                    "executed_quantity": "0",
                    "expire_date": "",
                    "last_done": "",
                    "limit_offset": "",
                    "msg": "",
                    "order_id": "701276261045858304",
                    "order_type": 1,
                    "outside_rth": 0,
                    "price": "388",
                    "quantity": "100",
                    "side": 1,
                    "status": 16,
                    "stock_name": "腾讯控股",
                    "submitted_at": "1650426089",
                    "symbol": "700.HK",
                    "tag": 1,
                    "time_in_force": 0,
                    "trailing_amount": "",
                    "trailing_percent": "",
                    "trigger_at": "0",
                    "trigger_price": "",
                    "trigger_status": 0,
                    "updated_at": "1650442225",
                  },
                ],
            },
        }
definitions:
  orders:
    properties:
      orders:
        type: "arrary"
        description: 订单信息
        properties:
          order_id:
            type: "string"
            description: 订单 ID
          status:
            type: "string"
            description: 订单状态
          stock_name:
            type: "string"
            description: 股票名称
          quantity:
            type: "string"
            description: 下单数量
          executed_qty:
            type: "string"
            description: 成交数量
          price:
            type: "string"
            description: 下单价格
          executed_price:
            type: "string"
            description: 成交价格
          submitted_at:
            type: "string"
            description: 下单时间
          side:
            type: "string"
            description: 买卖方向
          symbol:
            type: "string"
            description: 股票代码
          order_type:
            type: "string"
            description: 订单类型
          last_done:
            type: "string"
            description: 最近成交价格
          trigger_price:
            type: "string"
            description: "`LIT` / `MIT` 订单触发价格"
          msg:
            type: "string"
            description: 拒绝信息或备注
          tag:
            type: "string"
            description: 订单标记
          time_in_force:
            type: "string"
            description: 订单有效期类型
          expire_date:
            type: "string"
            description: 长期单的有效时间
          updated_at:
            type: "string"
            description: 最近更新时间
          trigger_at:
            type: "string"
            description: 条件单触发时间
          trailing_amount:
            type: "string"
            description: 条件单跟踪金额
          trailing_percent:
            type: "string"
            description: 条件单跟踪涨跌幅
          limit_offset:
            type: "string"
            description: 指定价差
          trigger_status:
            type: "string"
            description: 条件单触发状态
          currency:
            type: "string"
            description: 结算货币
          outside_rth:
            type: "string"
            description: 是否允许盘前盘后
