swagger: "2.0"
info:
  description: "订单撤单"
  version: "v1"
  title: "撤单"
paths:
  /v1/trade/order:
    delete:
      access: "交易权限"
      parameters:
        - name: "order_id"
          type: "string"
          description: "订单 ID"
          required: true
      responses:
        "200":
          description: "提交成功，订单已委托."
        "400":
          description: "下单被拒绝，请求参数错误."
      request_body:
        type: "python"
        value: |
          def example():
            from longbridge.http import *
            auth = Auth("${API_KEY}", "${API_KEY_SECRET}", "${TOKEN}")
            config = Config(base_url = "https://open.longbridgeapp.com/")
            client = Client(auth, config)
            result = client.put("/v1/openapi/trade/order")
      response_body: { "code": 0, "data": { "message": "Success" } }
