swagger: "2.0"
info:
  description: "This API is used to get history executions"
  version: "v1"
  title: "Get History Executions"
paths:
  /v1/trade/execution/history:
    get:
      access: "Trading Permissions"
      parameters:
        - name: "symbol"
          type: "string"
          in: query
          description: "Stock symbol, use `ticker.region` format, example: `AAPL.US`"
          required: false
        - name: "start_at"
          type: "string"
          in: query
          required: false
          description: "Start time, formatted as a timestamp (second), example: `1650410999`"
        - name: "end_at"
          type: "string"
          in: query
          required: false
          description: "End time, formatted as a timestamp (second), example: `1650410999`"
      responses:
        "200":
          description: "Get History Executions Success"
          schema:
            $ref: "#/definitions/history_executions_rsp"
        "400":
          description: "The query failed with an error in the request parameter."
      request_body:
        type: "python"
        value: |
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.longbridge.global"))

          resp = http.get("/v1/trade/execution/history")
          print(json.dumps(resp.data, indent=2))
      response_body:
        {
          "code": 0,
          "message": "success",
          "data":
            {
              "has_more": false,
              "trades":
                [
                  {
                    "order_id": "693664675163312128",
                    "price": "388",
                    "quantity": "100",
                    "symbol": "700.HK",
                    "trade_done_at": "1648611351",
                    "trade_id": "693664675163312128-1648611351433741210",
                  },
                ],
            },
        }
definitions:
  history_executions_rsp:
    properties:
      orders:
        type: "arrary"
        description: Execution Detail
        properties:
          order_id:
            type: "string"
            description: Order ID
          trade_id:
            type: "string"
            description: Execution ID
          symbol:
            type: "string"
            description: "Stock symbol, use `ticker.region` format,example: `AAPL.US`"
          trade_done_at:
            type: "string"
            description: Trade done time, formatted as a timestamp (second)
          quantity:
            type: "string"
            description: Executed quantity
          price:
            type: "string"
            description: Executed price
