swagger: "2.0"
info:
  description: "This API is used to get today executions"
  version: "v1"
  title: "Get Today Executions"
paths:
  /v1/trade/execution/today:
    get:
      access: "Trading Permissions"
      parameters:
        - name: "symbol"
          type: "string"
          in: query
          description: "Stock symbol, use `ticker.region` format, example: `AAPL.US`"
          required: false
        - name: "order_id"
          type: "string"
          required: false
          description: "Order ID, example: `701276261045858304`"
      responses:
        "200":
          description: "Get Today Executions Success"
          schema:
            $ref: "#/definitions/executions"
        "400":
          description: "The query failed with an error in the request parameter."
      request_body:
        type: "python"
        value: |
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.longbridgeapp.com"))

          query = {
            'symbol': '700.HK',
          }

          resp = http.get("/v1/trade/execution/today", query)
          print(json.dumps(resp.data, indent=2))
      response_body:
        {
          "code": 0,
          "message": "success",
          "data":
            {
              "trades":
                [
                  {
                    "order_id": "693664675163312128",
                    "price": "388",
                    "quantity": "100",
                    "symbol": "700.HK",
                    "trade_done_at": "1648611351",
                    "trade_id": "693664675163312128-1648611351433741210",
                  },
                ],
            },
        }
definitions:
  today_executions_rsp:
    properties:
      orders:
        type: "object[]"
        description: Execution Detail
        properties:
          order_id:
            type: "string"
            description: Order ID
          trade_id:
            type: "string"
            description: Execution ID
          symbol:
            type: "string"
            description: "Stock symbol, use `ticker.region` format, example: `AAPL.US`"
          trade_done_at:
            type: "string"
            description: Trade done time, formatted as a timestamp (second)
          quantity:
            type: "string"
            description: Executed quantity
          price:
            type: "string"
            description: Executed price
