swagger: "2.0"
info:
  description: "该接口用于获取包括账户、基金代码、持有份额、成本净值、当前净值、币种在内的基金持仓信息"
  version: "v1"
  title: "获取基金持仓"
paths:
  /v1/asset/fund:
    get:
      access:
      parameters:
        - name: "symbol"
          type: "string[]"
          description: 基金代码，使用 `ISIN` 格式，例如：`HK0000676327` <a href="https://en.wikipedia.org/wiki/International_Securities_Identification_Number">ISIN 解释</a>
          required: false
      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/fund_rsp"
        "400":
          description: "内部错误"
      request_body:
        type: "python"
        value: |
          # 获取基金持仓
          # https://open.longbridgeapp.com/docs/trade/asset/fund
          import os
          import json
          from longbridge.http import Auth, Config, HttpClient

          auth = Auth(os.getenv("LONGBRIDGE_APP_KEY"), os.getenv("LONGBRIDGE_APP_SECRET"), access_token=os.getenv("LONGBRIDGE_ACCESS_TOKEN"))
          http = HttpClient(auth, Config(base_url="https://openapi.longbridgeapp.com"))

          resp = http.get("/v1/asset/fund")
          print(json.dumps(resp.data, indent=2))
      response_body:
        {
          "code": 0,
          "data":
            {
              "list":
                [
                  {
                    "account_channel": "lb",
                    "fund_info":
                      [
                        {
                          "symbol": "HK0000447943",
                          "symbol_name": "高腾亚洲收益基金",
                          "currency": "USD",
                          "holding_units": "5.000",
                          "current_net_asset_value": "0",
                          "cost_net_asset_value": "0.00",
                          "net_asset_value_day": 1649865600,
                        },
                      ],
                  },
                ],
            },
        }

definitions:
  fund_rsp:
    properties:
      list:
        type: "object[]"
        description: "股票持仓信息"
        properties:
          account_channel:
            type: string
            description: 账户类型
          fund_info:
            type: "object[]"
            description: 基金详情
            properties:
              symbol:
                type: "string"
                description: 基金 ISIN 代码
              current_net_asset_value:
                type: "string"
                description: 当前净值
              net_asset_value_day:
                type: "string"
                description: 当前净值时间
              symbol_name:
                type: "string"
                description: 基金名称
              currency:
                type: "string"
                description: 币种
              cost_net_asset_value:
                type: "string"
                description: 成本净值
